#! /bin/sh

#---------------------------------------------------------------------
#                          check-up-to-date                           
# 
# Takes no arguments.  Determine whether the project starting from
# the current directory is up-to-date with the repository.
#---------------------------------------------------------------------

test -z "${FW_TRACE}" || set -x

prog="`which git 2>/dev/null`"

test -z "$prog" && {
  echo "revision/git/check-up-to-date: fatal: git not installed" 1>&2
  exit 1
}

if git status | grep -q ':'
  then
    exit 1
  else
    exit 0
  fi
