#!/bin/bash

###
# use ':' as separator, otherwise the following loop will fail
AIR_TESTS=""
AUTOGAIN_TESTS=""
CHROMA_TESTS=""
DENOISER_TESTS=""
EQHACK_TESTS=""
GAIN12_TESTS=""
GAIN24_TESTS=""
GAIN60_TESTS=""
GHOST_TESTS=""
GHOSTVIEWER_TESTS=""
IMPULSES_TESTS=""
LOFI_TESTS=""
PITCHSHIFT_TESTS=""
PRECEDENCE_TESTS=""
REBALANCE_TESTS="BL-Rebalance:04"
SAMPLEDELAY_TESTS=""
SATURATE_TESTS=""
SHAPER_TESTS=""
SINE_TESTS=""
SPATIALIZER_TESTS=""
SPECTRALDIFF_TESTS=""
STEREOPAN_TESTS=""
STEREOWIDTH_TESTS=""
TRANSIENT_TESTS=""
WAVES_TESTS=""

###
BUFFER_SIZES="1024"
