include(${IPLUG2_DIR}/Scripts/cmake/WDL.cmake)
include(${IPLUG2_DIR}/BL-Dependencies/bluelab-lib.cmake)
include(${IPLUG2_DIR}/BL-Dependencies/CrossoverFilter.cmake)
include(${IPLUG2_DIR}/BL-Dependencies/darknet.cmake)
include(${IPLUG2_DIR}/BL-Dependencies/Decimator.cmake)
include(${IPLUG2_DIR}/BL-Dependencies/DSP-Cpp-filters.cmake)
include(${IPLUG2_DIR}/BL-Dependencies/fastapprox.cmake)
include(${IPLUG2_DIR}/BL-Dependencies/flac.cmake)
include(${IPLUG2_DIR}/BL-Dependencies/fmem.cmake)
#include(${IPLUG2_DIR}/BL-Dependencies/fastapprox.cmake)
include(${IPLUG2_DIR}/BL-Dependencies/freeverb.cmake)
include(${IPLUG2_DIR}/BL-Dependencies/glm.cmake)
include(${IPLUG2_DIR}/BL-Dependencies/hungarian.cmake)
include(${IPLUG2_DIR}/BL-Dependencies/ini_parser.cmake)
include(${IPLUG2_DIR}/BL-Dependencies/KalmanFilter.cmake)
include(${IPLUG2_DIR}/BL-Dependencies/libdct.cmake)
include(${IPLUG2_DIR}/BL-Dependencies/libebur128.cmake)
include(${IPLUG2_DIR}/BL-Dependencies/libsamplerate.cmake)
include(${IPLUG2_DIR}/BL-Dependencies/libsndfile.cmake)
include(${IPLUG2_DIR}/BL-Dependencies/r8brain.cmake)
include(${IPLUG2_DIR}/BL-Dependencies/RandomSequence.cmake)
include(${IPLUG2_DIR}/BL-Dependencies/RTConvolve.cmake)
include(${IPLUG2_DIR}/BL-Dependencies/sndfilter.cmake)
include(${IPLUG2_DIR}/BL-Dependencies/OpenBLAS.cmake)

function(bl_add_all_libs target)
  
  iplug_target_add(${target} PUBLIC INCLUDE _wdl LINK _wdl)
  iplug_target_add(${target} PUBLIC INCLUDE _bluelab-lib LINK _bluelab-lib)
  iplug_target_add(${target} PUBLIC INCLUDE _crossover_filter LINK _crossover_filter)
  iplug_target_add(${target} PUBLIC INCLUDE _darknet LINK _darknet)
  iplug_target_add(${target} PUBLIC INCLUDE _decimator LINK _decimator)
  iplug_target_add(${target} PUBLIC INCLUDE _dsp_cpp_filters LINK _dsp_cpp_filters)
  iplug_target_add(${target} PUBLIC INCLUDE _flac LINK _flac)
  iplug_target_add(${target} PUBLIC INCLUDE _fmem LINK _fmem)
  iplug_target_add(${target} PUBLIC INCLUDE _fastapprox LINK _fastapprox)
  iplug_target_add(${target} PUBLIC INCLUDE _freeverb LINK _freeverb)
  iplug_target_add(${target} PUBLIC INCLUDE _glm LINK _glm)
  iplug_target_add(${target} PUBLIC INCLUDE _hungarian LINK _hungarian)
  iplug_target_add(${target} PUBLIC INCLUDE _ini_parser LINK _ini_parser)
  iplug_target_add(${target} PUBLIC INCLUDE _kalman_filter LINK _kalman_filter)
  iplug_target_add(${target} PUBLIC INCLUDE _libdct LINK _libdct)
  iplug_target_add(${target} PUBLIC INCLUDE _libebur128 LINK _libebur128)
  iplug_target_add(${target} PUBLIC INCLUDE _libsamplerate LINK _libsamplerate)
  iplug_target_add(${target} PUBLIC INCLUDE _libsndfile LINK _libsndfile)
  iplug_target_add(${target} PUBLIC INCLUDE _r8brain LINK _r8brain)
  iplug_target_add(${target} PUBLIC INCLUDE _RandomSequence LINK _RandomSequence)
  iplug_target_add(${target} PUBLIC INCLUDE _RTConvolve LINK _RTConvolve)
  iplug_target_add(${target} PUBLIC INCLUDE _sndfilter LINK _sndfilter)
  iplug_target_add(${target} PUBLIC INCLUDE _OpenBLAS LINK _OpenBLAS)
endfunction()
