#define PLUG_NAME "BL-Morpho"
#define PLUG_MFR "BlueLab"
#define PLUG_VERSION_HEX 0x00060005
#define PLUG_VERSION_STR "6.0.5"
#define PLUG_UNIQUE_ID 'morp' // Generated by hand
#define PLUG_MFR_ID 'BlLa'
#define PLUG_URL_STR "http://www.bluelab-plugs.com"
#define PLUG_EMAIL_STR "contact@bluelab-plugs.com"
#define PLUG_COPYRIGHT_STR "Copyright 2021 BlueLab | Audio Plugins"
#define PLUG_CLASS_NAME Morpho

#define BUNDLE_NAME "BL-Morpho"
#define BUNDLE_MFR "BlueLab"
#define BUNDLE_DOMAIN "com"

#define SHARED_RESOURCES_SUBPATH "BL-Morpho"

#define PLUG_CHANNEL_IO "1-1 2-2"

#define PLUG_LATENCY 0
#define PLUG_TYPE 0
#define PLUG_DOES_MIDI_IN 1 //0
#define PLUG_DOES_MIDI_OUT 0
#define PLUG_DOES_MPE 0
#define PLUG_DOES_STATE_CHUNKS 0
#define PLUG_HAS_UI 1
#define PLUG_WIDTH 1024
#define PLUG_HEIGHT 720
// Origin IPlug2: 60:
// Origin Gain12: 25
// For Windows + VSynch
#define PLUG_FPS 60
#define PLUG_SHARED_RESOURCES 0
#define PLUG_HOST_RESIZE 0

#define AUV2_ENTRY Morpho_Entry
#define AUV2_ENTRY_STR "Morpho_Entry"
#define AUV2_FACTORY Morpho_Factory
#define AUV2_VIEW_CLASS Morpho_View
#define AUV2_VIEW_CLASS_STR "Morpho_View"

#define AAX_TYPE_IDS 'IEF1', 'IEF2'
#define AAX_TYPE_IDS_AUDIOSUITE 'IEA1', 'IEA2'
#define AAX_PLUG_MFR_STR "BlLa"
#define AAX_PLUG_NAME_STR "Morpho\Morpho"
#define AAX_PLUG_CATEGORY_STR "Instrument"
#define AAX_DOES_AUDIOSUITE 1

#define VST3_SUBCATEGORY "Fx|Instrument"

#define APP_NUM_CHANNELS 2
#define APP_N_VECTOR_WAIT 0
#define APP_MULT 1
#define APP_COPY_AUV3 0
#define APP_SIGNAL_VECTOR_SIZE 64

// Necessary!
#define ROBOTO_FN "Roboto-Regular.ttf"

#define FONT_REGULAR_FN "font-regular.ttf"
#define FONT_LIGHT_FN "font-light.ttf"
#define FONT_BOLD_FN "font-bold.ttf"

#define FONT_OPENSANS_EXTRA_BOLD_FN "OpenSans-ExtraBold.ttf"
#define FONT_ROBOTO_BOLD_FN "Roboto-Bold.ttf"

#define FONT_OPENSANS_BOLD_FN "OpenSans-Bold.ttf"

#define MANUAL_FN "BL-Morpho_manual-EN.pdf"
// For WIN32
#define MANUAL_FULLPATH_FN "manual\BL-Morpho_manual-EN.pdf"

#define DUMMY_RESOURCE_FN "dummy.txt"

// Image resource locations for this plug.
#define PLUGNAME_FN "plugname.png"
#define HELP_BUTTON_FN "help-button.png"
#define TEXTFIELD_FN "textfield.png"
#define CHECKBOX_FN "checkbox.png"
#define KNOB_SMALL_FN "knob-small.svg"

// Common
#define BUTTON_SOURCES_FN "button-sources.png"
#define BUTTON_SYNTHESIS_FN "button-synthesis.png"

// Source panel
#define BACKGROUND_SO_FN "background_so.png"

#define GRAPH_SPECTRO_SO_FN "graph-spectro-so.png"
#define GRAPH_WATERFALL_SO_FN "graph-waterfall-so.png"

#define BUTTON_LIVE_SOURCE_FN "button-live-source.png"
#define BUTTON_FILE_SOURCE_FN "button-file-source.png"

#define BUTTON_APPLY_FN "button-apply.png"


#define BUTTON_PLAY_FN "button-play.png"

#define BUTTON_SELDIR_BOTH_FN "button-seldir-both.png"
#define BUTTON_SELDIR_HORIZ_FN "button-seldir-horiz.png"
#define BUTTON_SELDIR_VERT_FN "button-seldir-vert.png"

// Synthesis panel
#define BACKGROUND_SY_FN "background_sy.png"

#define GRAPH_WATERFALL_SY_FN "graph-waterfall-sy.png"

#define BUTTON_MUTE_FN "button-mute.png"
#define BUTTON_SOLO_FN "button-solo.png"

#define LABEL_SOURCE_NAME_FN "label-source-name.png"
#define LABEL_SOURCE_ICONS_FN "label-source-icons.png"

#define PAD_TRACK_SY_FN "pad-track-sy.png"
#define PAD_HANDLE0_FN "pad-handle0.png"
#define PAD_HANDLE1_FN "pad-handle1.png"
#define PAD_HANDLE2_FN "pad-handle2.png"
#define PAD_HANDLE3_FN "pad-handle3.png"
#define PAD_HANDLE4_FN "pad-handle4.png"
#define PAD_HANDLE5_FN "pad-handle5.png"
